const GET_BLOOD_CAMPS = 'GET_BLOOD_CAMPS'
const GET_BLOOD_CAMPS_SUCCESS = 'GET_BLOOD_CAMPS_SUCCESS'
const GET_BLOOD_CAMPS_FAILURE = 'GET_BLOOD_CAMPS_FAILURE'

const GET_NEARBY_BLOOD_CAMPS = 'GET_NEARBY_BLOOD_CAMPS'
const GET_NEARBY_BLOOD_CAMPS_SUCCESS = 'GET_NEARBY_BLOOD_CAMPS_SUCCESS'
const GET_NEARBY_BLOOD_CAMPS_FAILURE = 'GET_NEARBY_BLOOD_CAMPS_FAILURE'

export {
  GET_BLOOD_CAMPS,
  GET_BLOOD_CAMPS_SUCCESS,
  GET_BLOOD_CAMPS_FAILURE,
  GET_NEARBY_BLOOD_CAMPS,
  GET_NEARBY_BLOOD_CAMPS_SUCCESS,
  GET_NEARBY_BLOOD_CAMPS_FAILURE
}