const GET_BLOOD_BANKS = 'GET_BLOOD_BANKS'
const GET_BLOOD_BANKS_SUCCESS = 'GET_BLOOD_BANKS_SUCCESS'
const GET_BLOOD_BANKS_FAILURE = 'GET_BLOOD_BANKS_FAILURE'

const GET_NEARBY_BLOOD_BANKS = 'GET_NEARBY_BLOOD_BANKS'
const GET_NEARBY_BLOOD_BANKS_SUCCESS = 'GET_NEARBY_BLOOD_BANKS_SUCCESS'
const GET_NEARBY_BLOOD_BANKS_FAILURE = 'GET_NEARBY_BLOOD_BANKS_FAILURE'

export {
  GET_BLOOD_BANKS,
  GET_BLOOD_BANKS_SUCCESS,
  GET_BLOOD_BANKS_FAILURE,
  GET_NEARBY_BLOOD_BANKS,
  GET_NEARBY_BLOOD_BANKS_SUCCESS,
  GET_NEARBY_BLOOD_BANKS_FAILURE
}