const GET_BLOOD_PACKS = 'GET_BLOOD_PACKS'
const GET_BLOOD_PACKS_SUCCESS = 'GET_BLOOD_PACKS_SUCCESS'
const GET_BLOOD_PACKS_FAILURE = 'GET_BLOOD_PACKS_FAILURE'

export {
  GET_BLOOD_PACKS,
  GET_BLOOD_PACKS_SUCCESS,
  GET_BLOOD_PACKS_FAILURE
}

