const GET_BLOOD_CAMPS = 'GET_BLOOD_CAMPS'
const GET_BLOOD_CAMPS_SUCCESS = 'GET_BLOOD_CAMPS_SUCCESS'
const GET_BLOOD_CAMPS_FAILURE = 'GET_BLOOD_CAMPS_FAILURE'

export {
  GET_BLOOD_CAMPS, GET_BLOOD_CAMPS_SUCCESS, GET_BLOOD_CAMPS_FAILURE
}