const GET_BLOOD_TESTS = 'GET_BLOOD_TESTS'
const GET_BLOOD_TESTS_SUCCESS = 'GET_BLOOD_TESTS_SUCCESS'
const GET_BLOOD_TESTS_FAILURE = 'GET_BLOOD_TESTS_FAILURE'

const GET_NEARBY_BLOOD_TESTS = 'GET_NEARBY_BLOOD_TESTS'
const GET_NEARBY_BLOOD_TESTS_SUCCESS = 'GET_NEARBY_BLOOD_TESTS_SUCCESS'
const GET_NEARBY_BLOOD_TESTS_FAILURE = 'GET_NEARBY_BLOOD_TESTS_FAILURE'

export {
  GET_BLOOD_TESTS,
  GET_BLOOD_TESTS_SUCCESS,
  GET_BLOOD_TESTS_FAILURE,
  GET_NEARBY_BLOOD_TESTS,
  GET_NEARBY_BLOOD_TESTS_SUCCESS,
  GET_NEARBY_BLOOD_TESTS_FAILURE
}