const GET_BLOOD_SEPARATIONS = 'GET_BLOOD_SEPARATIONS'
const GET_BLOOD_SEPARATIONS_SUCCESS = 'GET_BLOOD_SEPARATIONS_SUCCESS'
const GET_BLOOD_SEPARATIONS_FAILURE = 'GET_BLOOD_SEPARATIONS_FAILURE'

export {
  GET_BLOOD_SEPARATIONS, GET_BLOOD_SEPARATIONS_SUCCESS, GET_BLOOD_SEPARATIONS_FAILURE
}