const GET_BLOOD_PACKS = 'GET_BLOOD_PACKS'
const GET_BLOOD_PACKS_SUCCESS = 'GET_BLOOD_PACKS_SUCCESS'
const GET_BLOOD_PACKS_FAILURE = 'GET_BLOOD_PACKS_FAILURE'

const GET_TRANSFER_HISTORIES = 'GET_TRANSFER_HISTORIES'
const GET_TRANSFER_HISTORIES_SUCCESS = 'GET_TRANSFER_HISTORIES_SUCCESS'
const GET_TRANSFER_HISTORIES_FAILURE = 'GET_TRANSFER_HISTORIES_FAILURE'


export {
  GET_BLOOD_PACKS,
  GET_BLOOD_PACKS_SUCCESS,
  GET_BLOOD_PACKS_FAILURE,
  GET_TRANSFER_HISTORIES,
  GET_TRANSFER_HISTORIES_SUCCESS,
  GET_TRANSFER_HISTORIES_FAILURE
}

