const GET_CAMPAIGNS = 'GET_CAMPAIGNS'
const GET_CAMPAIGNS_SUCCESS = 'GET_CAMPAIGNS_SUCCESS'
const GET_CAMPAIGNS_FAILURE = 'GET_CAMPAIGNS_FAILURE'

export {
  GET_CAMPAIGNS, GET_CAMPAIGNS_SUCCESS, GET_CAMPAIGNS_FAILURE
}