const GET_CAMPAIGNS = 'GET_CAMPAIGNS'
const GET_CAMPAIGNS_SUCCESS = 'GET_CAMPAIGNS_SUCCESS'
const GET_CAMPAIGNS_FAILURE = 'GET_CAMPAIGNS_FAILURE'

const GET_CAMPAIGNS_BY_NAME = 'GET_CAMPAIGNS_BY_NAME'
const GET_CAMPAIGNS_BY_NAME_SUCCESS = 'GET_CAMPAIGNS_BY_NAME_SUCCESS'
const GET_CAMPAIGNS_BY_NAME_FAILURE = 'GET_CAMPAIGNS_BY_NAME_FAILURE'

export {
  GET_CAMPAIGNS,
  GET_CAMPAIGNS_SUCCESS,
  GET_CAMPAIGNS_FAILURE,
  GET_CAMPAIGNS_BY_NAME,
  GET_CAMPAIGNS_BY_NAME_SUCCESS,
  GET_CAMPAIGNS_BY_NAME_FAILURE
}