const GET_HOSPITALS = 'GET_HOSPITALS'
const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS'
const GET_HOSPITALS_FAILURE = 'GET_HOSPITALS_FAILURE'

const GET_NEARBY_HOSPITALS = 'GET_NEARBY_HOSPITALS'
const GET_NEARBY_HOSPITALS_SUCCESS = 'GET_NEARBY_HOSPITALS_SUCCESS'
const GET_NEARBY_HOSPITALS_FAILURE = 'GET_NEARBY_HOSPITALS_FAILURE'

const GET_HOSPITALS_BY_NAME = 'GET_HOSPITAL_BY_NAME'
const GET_HOSPITALS_BY_NAME_SUCCESS = 'GET_HOSPITAL_BY_NAME_SUCCESS'
const GET_HOSPITALS_BY_NAME_FAILURE = 'GET_HOSPITAL_BY_NAME_FAILURE'

export {
  GET_HOSPITALS,
  GET_HOSPITALS_SUCCESS,
  GET_HOSPITALS_FAILURE,
  GET_NEARBY_HOSPITALS,
  GET_NEARBY_HOSPITALS_SUCCESS,
  GET_NEARBY_HOSPITALS_FAILURE,
  GET_HOSPITALS_BY_NAME,
  GET_HOSPITALS_BY_NAME_SUCCESS,
  GET_HOSPITALS_BY_NAME_FAILURE
}