const GET_HOSPITALS = 'GET_HOSPITALS'
const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS'
const GET_HOSPITALS_FAILURE = 'GET_HOSPITALS_FAILURE'

const GET_NEARBY_HOSPITALS = 'GET_NEARBY_HOSPITALS'
const GET_NEARBY_HOSPITALS_SUCCESS = 'GET_NEARBY_HOSPITALS_SUCCESS'
const GET_NEARBY_HOSPITALS_FAILURE = 'GET_NEARBY_HOSPITALS_FAILURE'

export {
  GET_HOSPITALS,
  GET_HOSPITALS_SUCCESS,
  GET_HOSPITALS_FAILURE,
  GET_NEARBY_HOSPITALS,
  GET_NEARBY_HOSPITALS_SUCCESS,
  GET_NEARBY_HOSPITALS_FAILURE
}