const GET_HOSPITALS = 'GET_HOSPITALS'
const GET_HOSPITALS_SUCCESS = 'GET_HOSPITALS_SUCCESS'
const GET_HOSPITALS_FAILURE = 'GET_HOSPITALS_FAILURE'

export {
  GET_HOSPITALS, GET_HOSPITALS_SUCCESS, GET_HOSPITALS_FAILURE
}