const GET_VOUCHERS = 'GET_VOUCHERS';
const GET_VOUCHERS_SUCCESS = 'GET_VOUCHERS_SUCCESS';
const GET_VOUCHERS_FAILURE = 'GET_VOUCHERS_FAILURE';

const GET_ETHEREUMS = 'GET_ETHEREUMS';
const GET_ETHEREUMS_SUCCESS = 'GET_ETHEREUMS_SUCCESS';
const GET_ETHEREUMS_FAILURE = 'GET_ETHEREUMS_FAILURE';

const REDEEM_VOUCHER = 'REDEEM_VOUCHER';
const REDEEM_VOUCHER_SUCCESS = 'REDEEM_VOUCHER_SUCCESS';
const REDEEM_VOUCHER_FAILURE = 'REDEEM_VOUCHER_FAILURE';

const REDEEM_ETHEREUM = 'REDEEM_ETHEREUM';
const REDEEM_ETHEREUM_SUCCESS = 'REDEEM_ETHEREUM_SUCCESS';
const REDEEM_ETHEREUM_FAILURE = 'REDEEM_ETHEREUM_FAILURE';


export {
  GET_VOUCHERS,
  GET_VOUCHERS_SUCCESS,
  GET_VOUCHERS_FAILURE,
  GET_ETHEREUMS,
  GET_ETHEREUMS_SUCCESS,
  GET_ETHEREUMS_FAILURE,
  REDEEM_VOUCHER,
  REDEEM_VOUCHER_SUCCESS,
  REDEEM_VOUCHER_FAILURE,
  REDEEM_ETHEREUM,
  REDEEM_ETHEREUM_SUCCESS,
  REDEEM_ETHEREUM_FAILURE
}
