const GET_VOUCHERS = 'GET_VOUCHERS';
const GET_VOUCHERS_SUCCESS = 'GET_VOUCHERS_SUCCESS';
const GET_VOUCHERS_FAILURE = 'GET_VOUCHERS_FAILURE';

const GET_ETHEREUMS = 'GET_ETHEREUMS';
const GET_ETHEREUMS_SUCCESS = 'GET_ETHEREUMS_SUCCESS';
const GET_ETHEREUMS_FAILURE = 'GET_ETHEREUMS_FAILURE';

export {
  GET_VOUCHERS, GET_VOUCHERS_SUCCESS, GET_VOUCHERS_FAILURE, GET_ETHEREUMS, GET_ETHEREUMS_SUCCESS, GET_ETHEREUMS_FAILURE
}
