const GET_USER_INFO = 'GET_USER_INFO';
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export {
  GET_USER_INFO, GET_USER_INFO_SUCCESS, GET_USER_INFO_FAILURE
}
