const GET_USER_INFO = 'GET_USER_INFO';
const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

const GET_USER_POINT = 'GET_USER_POINT';
const GET_USER_POINT_SUCCESS = 'GET_USER_POINT_SUCCESS';
const GET_USER_POINT_FAILURE = 'GET_USER_POINT_FAILURE';

const GET_POINTS_HISTORIES = 'GET_POINTS_HISTORIES';
const GET_POINTS_HISTORIES_SUCCESS = 'GET_POINTS_HISTORIES_SUCCESS';
const GET_POINTS_HISTORIES_FAILURE = 'GET_POINTS_HISTORIES_FAILURE';

export {
  GET_USER_INFO,
  GET_USER_INFO_SUCCESS,
  GET_USER_INFO_FAILURE,
  GET_USER_POINT,
  GET_USER_POINT_SUCCESS,
  GET_USER_POINT_FAILURE,
  GET_POINTS_HISTORIES,
  GET_POINTS_HISTORIES_SUCCESS,
  GET_POINTS_HISTORIES_FAILURE
}
